DROP TABLE IF EXISTS BRANCH;
CREATE TABLE BRANCH(
	BRANCH_ID	INTEGER			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	BRANCH_NAME	VARCHAR(20)		NOT NULL
);

DROP TABLE IF EXISTS DEPT;
CREATE TABLE DEPT(
	DEPT_ID		INTEGER			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DEPT_NAME	VARCHAR(20)		NOT NULL
);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
	USER_ID		INTEGER			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LOGIN_ID	VARCHAR(20)		NOT NULL,
	PASSWORD	VARCHAR(255)	NOT NULL,
	USER_NAME	VARCHAR(10)		NOT NULL,
	BRANCH_ID	INTEGER			NOT NULL,
	DEPT_ID		INTEGER			NOT NULL,
	LOCK_FLG	INTEGER			DEFAULT 0
);

DROP TABLE IF EXISTS POST;
CREATE TABLE POST(
	POST_ID		INTEGER			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	POST_TITLE	VARCHAR(50)		NOT NULL,
	TEXT		TEXT			NOT NULL,
	CATEGORY	VARCHAR(10)		NOT NULL,
	INSERT_DATE TIMESTAMP		,
	USER_NAME	VARCHAR(10)		NOT NULL
);

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT(
	COMMENT_ID	INTEGER			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TEXT		TEXT			NOT NULL,
	INSERT_DATE TIMESTAMP		,
	USER_NAME	VARCHAR(10)		NOT NULL,
	POST_ID		INTEGER
);

INSERT INTO BRANCH (BRANCH_NAME) VALUES ('ñ{é–');
INSERT INTO BRANCH (BRANCH_NAME) VALUES ('ìåãûéxìX');
INSERT INTO BRANCH (BRANCH_NAME) VALUES ('â´ìÍéxìX');
INSERT INTO BRANCH (BRANCH_NAME) VALUES ('ñkäCìπéxìX');

INSERT INTO DEPT (DEPT_NAME) VALUES ('ä«óùé“');
INSERT INTO DEPT (DEPT_NAME) VALUES ('ëçñ±êléñíSìñé“');
INSERT INTO DEPT (DEPT_NAME) VALUES ('èÓïÒä«óùíSìñé“');
INSERT INTO DEPT (DEPT_NAME) VALUES ('éxìXí∑');
INSERT INTO DEPT (DEPT_NAME) VALUES ('é–àı');

INSERT INTO USER (LOGIN_ID,PASSWORD,USER_NAME,BRANCH_ID,DEPT_ID) 
			VALUES ('admin','admin','ä«óùé“',1,1);
